language: php
dist: trusty

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.2

install:
  - composer install --prefer-dist

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

script:
  - ./vendor/bin/phpunit --configuration phpunit.dist.xml